sincehence/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    CustomLoginView,
    # CustomPasswordChangeView,
    # CustomPasswordChangeDoneView,   
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
    webmanifest
    # page_not_found
    ) 


# handler404 = page_not_found


urlpatterns = [
    path('admin/', admin.site.urls),   
    path('accounts/login/', CustomLoginView.as_view(), name='login'),    
    path('accounts/password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('accounts/reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),    
    path('accounts/reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),  
    path('', include('sincehence_core.urls')), 
    path('consent/', include('policy_concent.urls')),     
    path('summernote/', include('django_summernote.urls')),  
]

urlpatterns += [    
    path('webmanifest/', webmanifest, name='webmanifest'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    

sincehence_core/urls.py
from django.urls import path, include
from .views import *
from django.contrib.sitemaps.views import sitemap
from .sitemaps import *
from django.views.generic.base import TemplateView

app_name = 'sincehence_core'

sitemap_list = {
    'static': StaticSitemap,
    'pages' : PageSitemap,
    'category' : CategorySitemap,
    'BlogSitemap' : BlogSitemap
}

urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemap_list}, name='django.contrib.sitemaps.views.sitemap'),      
    path('', home, name='home'),
    path('contact/', contact, name='contact'),    
    path('b/<str:slug>', blog_detail, name='blog_details'),
    path('latest/blogs/', latest_blogs, name='latest_blogs'),       
    path('<str:username>/blogs/', user_blogs, name='user_blogs'), 
    path('category/<str:slug>', category_detail, name='category_detail'),    
    path('archive/<int:year>/<int:month>', archive_detail, name='archive_detail'),   
    path('p/<str:slug>', page_detail, name='page_detail'),   
    
]

templates/core/blog_detail.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block extra_head %}

{% endblock %}   



{% block about %} 

    <main class="page-wrapper">
        <!-- Start Advance Pricing Area  -->
        <div class="rainbow-blog-details-area">
            <div class="post-page-banner rainbow-section-gapTop">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 offset-lg-2">
                            <div class="content text-center">
                                <div class="page-title">
                                    <h1 class="theme-gradient">{{blog.title}}</h1>
                                </div>
                                <ul class="rainbow-meta-list">
                                    <li>
                                        <i class="feather-user"></i>
                                        <a href="{% url 'sincehence_core:user_blogs' blog.creator.username %}">{{blog.creator.username}}</a>
                                    </li>
                                    <li>
                                        <i class="feather-calendar"></i>
                                        {{blog.updated_at|date:"F j, Y" }}
                                    </li>
                                    
                                </ul>
                                <div class="thumbnail alignwide mt--60"><img class="w-100 radius" src="{{blog.feature.url}}" alt="{{blog.title}}" title="{{blog.title}}"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="blog-details-content pt--60 rainbow-section-gapBottom">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-8 offset-lg-2">
                            <div class="content">

                               {{blog.body|safe}}

                               <div class="category-meta">
                               <ul class="rainbow-meta-list">                                
                                    <li class="btn">
                                        <a href="#">
                                        <i class="feather-eye"></i>
                                        {{blog.total_view }}
                                        </a>
                                    </li>                                   
                                </ul>
                                </div>


                                <div class="category-meta">
                                    <span class="text">Categories: </span>
                                    <div class="tagcloud">
                                        {% for cat in blog.categories.all %}
                                        <a href="{{ cat.get_absolute_url }}">{{cat.title}}</a>
                                        {% endfor %}
                                        
                                    </div>
                                </div>





                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Advance Pricing Area  -->



{% endblock %}

templates/core/category_details.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block extra_head %}

{% endblock %}   



{% block about %} 
        <div class="breadcrumb-area breadcarumb-style-1 ptb--120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="breadcrumb-inner text-center">
                            <h1 class="title theme-gradient h2">{{site_data.title}}</h1>
                            <p class="descriptiion">{{site_data.description}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Breadcarumb area  -->
        <!-- Start Theme Style  -->
        <div>
            <div class="rainbow-gradient-circle"></div>
            <div class="rainbow-gradient-circle theme-pink"></div>
        </div>
        <!-- End Theme Style  -->




        <!-- Start Blog List View  -->
        <div class="main-content">
            <div class="rainbow-blog-area rainbow-section-gap">
                <div class="container">
                    <div class="row row--30">
                        <div class="col-lg-8">
                            <div class="row mt_dec--30">
                                {% for blog in blogs %}
                                <div class="col-lg-12 mt--30">
                                    <div class="rainbow-card box-card-style-default card-list-view">
                                        <div class="inner">
                                            <div class="thumbnail">
                                                <a class="image" href="{{blog.get_absolute_url}}">
                                                    <img src="{{blog.feature.url}}" alt="{{blog.title}}" title="{{blog.title}}">
                                                </a>
                                            </div>
                                            <div class="content">
                                                <h4 class="title">
                                                    <a href="{{blog.get_absolute_url}}">{{blog.title}}</a>
                                                </h4>
                                                <ul class="rainbow-meta-list">
                                                    <li><a href="{% url 'sincehence_core:user_blogs' blog.creator.username %}">{{ blog.creator.username }}</a></li>
                                                    <li class="separator">/</li>
                                                    <li>{{blog.updated_at|date:"F j, Y" }}</li>
                                                </ul>
                                                {{ blog.body|safe|truncatechars:250 }}
                                            </div>
                                        </div>
                                    </div>
                                </div>                                
                                {% endfor %}        
                            </div>
                            {% include 'includes/pagination.html' with page=blogs %}  
                        </div>
                        <div class="col-lg-4 mt_md--40 mt_sm--40">
                            <aside class="rainbow-sidebar">
                                <div class="rbt-single-widget widget_search mt--40">
                                    <div class="inner">
                                        <form class="blog-search" method="GET">
                                            {{ search_form.as_p }}                                            
                                            <button type="submit" class="search-button">
                                                <i class="feather-search"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                                <div class="rbt-single-widget widget_categories mt--40">
                                    <h3 class="title">Categories</h3>
                                    <div class="inner">
                                        <ul class="category-list ">
                                            {% for cat in categories %}
                                            
                                            <li>
                                                <a class="{% if cat.get_absolute_url == request.path %} active {% endif %}" href="{{cat.get_absolute_url}}">
                                                    <span class="left-content">{{cat.title}}</span>
                                                    <span class="count-text">{{ cat.blog_count }}</span>
                                                </a>
                                            </li>
                                            {% endfor %}
                                            
                                        </ul>
                                    </div>
                                </div>
                                <div class="rbt-single-widget widget_recent_entries mt--40">
                                    <h3 class="title">Top Views</h3>
                                    <div class="inner">
                                        <ul>
                                            {% for b in top_views %}
                                            <li><a class="d-block" href="{{b.get_absolute_url}}">{{b.title}}({{b.total_view_count}}).</a>
                                            </li>
                                            {% endfor %}
                                            
                                        </ul>
                                    </div>
                                </div>
                                <div class="rbt-single-widget widget_archive mt--40">
                                    <h3 class="title">Archives</h3>
                                    <div class="inner">
                                        <ul>
                                            
                                            {% for ba in blog_archive %}
                                            {% url 'sincehence_core:archive_detail' year=ba.month|date:'Y' month=ba.month|date:'m' as archive_url %}                                          
                                            <li>
                                                <a href="{{ archive_url }}" class="cate {% if archive_url == request.path %}active{% endif %}">
                                                    {{ ba.month|date:"F Y" }}
                                                </a>
                                            </li>
                                            {% endfor %}
                                            
                                        </ul>
                                    </div>
                                </div>
                             
                            </aside>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Blog List View  -->

        {% endblock %}

templates/core/contact.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block extra_head %}
<style>
    #id_phone_number_0 {
        width: 200px;
        height: inherit;
    }
</style>
{% endblock %}   



{% block about %} 
    <!-- Start Contact Area  -->
    <div class="main-content">

        <div class="rainbow-contact-area rainbow-section-gap">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 mb--40">
                        <div class="section-title text-center" data-sal="slide-up" data-sal-duration="700" data-sal-delay="100">
                            <h4 class="subtitle "><span class="theme-gradient">Contact Form</span></h4>
                            <h2 class="title w-600 mb--20">{{site_data.title}}</h2>
                            <p class="description">{{site_data.description}}</p>
                        </div>
                    </div>
                </div>
                <div class="row row--15">
                    <div class="col-lg-12">
                        <div class="rainbow-contact-address mt_dec--30">
                            <div class="row">
                                <div class="col-lg-4 col-md-6 col-12 d-flex">
                                    <div class="rainbow-address flex-fill">
                                        <div class="icon">
                                            <i class="feather-headphones"></i>
                                        </div>
                                        <div class="inner">
                                            <h4 class="title">Contact Phone Number</h4>
                                            <p><a href="tel:{{site_data.phone}}">{{site_data.phone}}</a></p>
                                   
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-6 col-12 d-flex">
                                    <div class="rainbow-address flex-fill">
                                        <div class="icon">
                                            <i class="feather-mail"></i>
                                        </div>
                                        <div class="inner">
                                            <h4 class="title">Our Email Address</h4>
                                            <p><a href="mailto:admin@gmail.com">{{site_data.email}}</a></p>                                         
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-6 col-12 d-flex">
                                    <div class="rainbow-address flex-fill">
                                        <div class="icon">
                                            <i class="feather-map-pin"></i>
                                        </div>
                                        <div class="inner">
                                            <h4 class="title">Our Location</h4>
                                            <p>{{site_data.location|safe}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row mt--40 row--15">
                    <div class="col-lg-7">
                        <form class="contact-form-1" id="contact_form" method="POST">
                            {% csrf_token %}
                            <div class="form-group">                   
                                {{ form.name.errors }}
                                {{ form.name }}
                            </div>
                            <div class="form-group d-flex">
                                {{ form.phone_number.errors }}
                                {{ form.phone_number }}
                            </div>
                        
                            <div class="form-group">
                                {{ form.email.errors }}
                                {{ form.email }}
                            </div>

                            <div class="form-group">
                                {{ form.subject.errors }}
                                {{ form.subject }}
                            </div>

                            <div class="form-group">
                                {{ form.message.errors }}
                                {{ form.message }}
                            </div>

                            <div class="form-group">
                                <input name="submit" type="submit" id="submit" class="btn-default btn-medium btn-icon btn-border" value="Submit Now"/>
                            </div>
                        </form>
                    </div>
                    <div class="col-lg-5 mt_md--30 mt_sm--30">
                        <div class="google-map-style-1">
                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.231949306149!2d-0.09149527297786142!3d51.5273054092484!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x48761ca66eeaa42d%3A0xfeaa9eff15ff6f43!2sLondon%20EC1V%202NX%2C%20UK!5e0!3m2!1sen!2sbd!4v1687598976109!5m2!1sen!2sbd" width="600" height="550" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <!-- End Contact Area  -->
{% endblock %}

templates/core/page_detail.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block extra_head %}

{% endblock %}   



{% block about %} 

        <!-- Start Slider Area  -->
        <div class="slider-area slider-style-1 variation-default height-850 bg_image bg_image--12" style="background-image: url({{page.top_banenr.url}});" data-black-overlay="7">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="inner pt--80 text-center" data-sal="slide-up" data-sal-duration="400" data-sal-delay="150">
                            <div>
                                <h3 class="rainbow-sub-badge"><span class="theme-gradient">{{page.title}}.</span></h3>
                            </div>
                            <h1 class="title display-one">{{page.top_tagline|safe}}.</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End Slider Area  -->

        <!-- Start Service Area  -->
        <div class="service-area rainbow-section-gapTop">
            <div class="container">
                <div class="row">
                   
                    <div class="col-lg-12">
                        {{page.body|safe}}
                    </div>
                </div>
            </div>
        </div>
        <!-- End Service Area  -->



{% endblock %}